import jsPDF from "jspdf";
import QRCode from "qrcode";

/**
 * Generate official PDF for an application.
 * @param type - document type (e.g. "Resident Certificate", "Introduction Letter")
 * @param data - dynamic data (applicant info, dates, payment, etc.)
 * @param includePhoto - optional profile photo URL for intro letters
 */
export async function generateOfficialPDF(
  type: string,
  data: any,
  includePhoto?: string
) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });

  // 🏛️ HEADER
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("UNITED REPUBLIC OF TANZANIA", 105, 20, { align: "center" });
  doc.setFontSize(13);
  doc.text("LOCAL GOVERNMENT DIGITAL SERVICES PORTAL", 105, 27, {
    align: "center",
  });
  doc.setDrawColor(0);
  doc.line(20, 30, 190, 30);

  // 🧾 Document Title
  doc.setFontSize(15);
  doc.text(type.toUpperCase(), 105, 42, { align: "center" });
  doc.setFontSize(11);
  doc.text(`Application ID: ${data.applicationId}`, 105, 48, {
    align: "center",
  });

  // 🧍 Applicant Details
  doc.setFontSize(11);
  let y = 60;
  doc.text(`Full Name: ${data.fullName}`, 25, y);
  y += 7;
  doc.text(`NIDA ID: ${data.nida}`, 25, y);
  y += 7;
  doc.text(`Issued Date: ${data.issuedDate}`, 25, y);
  y += 7;
  doc.text(`Issued By: ${data.issuedBy}`, 25, y);

  // 🖼️ Profile Photo (Optional)
  if (includePhoto) {
    try {
      const img = await loadImage(includePhoto);
      doc.addImage(img, "JPEG", 150, 60, 35, 35);
    } catch {
      console.warn("Profile photo failed to load");
    }
  }

  // 📄 Document Body
  y += 15;
  doc.setFont("helvetica", "normal");
  doc.text(
    25,
    y,
    data.body ||
      "This document serves as an official confirmation of the applicant’s status, verified by the local government digital portal."
  );
  y += 15;

  // 💰 Payment Info (if applicable)
  if (data.payment) {
    doc.setFont("helvetica", "bold");
    doc.text("Payment Details", 25, y);
    y += 7;
    doc.setFont("helvetica", "normal");
    doc.text(`Amount Paid: ${data.payment.amount}`, 25, y);
    y += 7;
    doc.text(`Payment Date: ${data.payment.date}`, 25, y);
    y += 7;
    doc.text(`Transaction ID: ${data.payment.txId}`, 25, y);
    y += 10;
  }

  // 🔐 QR Code for verification
  const qrData = `Verify Document: ${data.applicationId} - ${data.fullName}`;
  const qrCode = await QRCode.toDataURL(qrData);
  doc.addImage(qrCode, "PNG", 160, 245, 30, 30);

  doc.setFontSize(9);
  doc.text("Scan the QR Code to verify authenticity online", 160, 278);

  // 🖋️ Signature
  doc.line(25, 265, 80, 265);
  doc.text("Authorized Signature", 25, 270);
  doc.text("Local Government Authority", 25, 275);

  // 🔄 Footer
  doc.setFontSize(8);
  doc.text(
    "Generated by Tanzania Local Government Digital Services Portal",
    105,
    290,
    { align: "center" }
  );

  doc.save(`${type.replace(/\s/g, "_")}_${data.applicationId}.pdf`);
}

// Utility: Load image as base64
function loadImage(url: string): Promise<string> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = "Anonymous";
    img.onload = () => {
      const canvas = document.createElement("canvas");
      canvas.width = img.width;
      canvas.height = img.height;
      const ctx = canvas.getContext("2d");
      if (!ctx) return reject("Canvas error");
      ctx.drawImage(img, 0, 0);
      resolve(canvas.toDataURL("image/jpeg"));
    };
    img.onerror = reject;
    img.src = url;
  });
}
